[package]
name = "dark-light"
version = "1.1.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/frewsxcv/rust-dark-light"
description = "Detect if dark mode or light mode is enabled"
readme = "README.md"
build = "build.rs"

[dependencies]
futures = "0.3"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "dragonfly", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
detect-desktop-environment = "1.1.0"
dconf_rs = "0.3"
zbus = { version = "4.4", optional = true }
ashpd = { version = "0.9", optional = true }
rust-ini = "0.21"
xdg = "2.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["MediaQueryList", "Window"] }

[features]
zbus = ["dep:zbus", "dep:ashpd"]
